/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestWasmIndexRouteImport } from './routes/test-wasm/index'
import { Route as AllotmentIndexRouteImport } from './routes/allotment/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestWasmIndexRoute = TestWasmIndexRouteImport.update({
  id: '/test-wasm/',
  path: '/test-wasm/',
  getParentRoute: () => rootRouteImport,
} as any)
const AllotmentIndexRoute = AllotmentIndexRouteImport.update({
  id: '/allotment/',
  path: '/allotment/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/allotment': typeof AllotmentIndexRoute
  '/test-wasm': typeof TestWasmIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/allotment': typeof AllotmentIndexRoute
  '/test-wasm': typeof TestWasmIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/allotment/': typeof AllotmentIndexRoute
  '/test-wasm/': typeof TestWasmIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/allotment' | '/test-wasm'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/allotment' | '/test-wasm'
  id: '__root__' | '/' | '/allotment/' | '/test-wasm/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AllotmentIndexRoute: typeof AllotmentIndexRoute
  TestWasmIndexRoute: typeof TestWasmIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-wasm/': {
      id: '/test-wasm/'
      path: '/test-wasm'
      fullPath: '/test-wasm'
      preLoaderRoute: typeof TestWasmIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/allotment/': {
      id: '/allotment/'
      path: '/allotment'
      fullPath: '/allotment'
      preLoaderRoute: typeof AllotmentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AllotmentIndexRoute: AllotmentIndexRoute,
  TestWasmIndexRoute: TestWasmIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
