packages:
  - scripts
  - packages/**

catalog:
  '@base-ui/react': 1.1.0
  '@biomejs/biome': ^2.3.11
  '@gltf-transform/core': ^4.3.0
  '@gltf-transform/extensions': ^4.3.0
  '@gltf-transform/functions': ^4.3.0
  '@inquirer/prompts': ^8.1.0
  '@phosphor-icons/react': ^2.1.10
  '@react-three/drei': ^10.7.7
  '@react-three/fiber': ^9.5.0
  '@redux-devtools/extension': ^3.3.0
  '@tailwindcss/vite': ^4.1.17
  '@tanstack/react-query': 5.90.12
  '@tanstack/react-router': ^1.140.1
  '@tanstack/react-router-devtools': ^1.140.1
  '@tanstack/router-plugin': ^1.140.1
  '@types/braces': ^3.0.5
  '@types/node': ^24.10.4
  '@types/react': ^19.2.7
  '@types/react-beforeunload': ^2.1.5
  '@types/react-dom': ^19.2.3
  '@types/three': ^0.182.0
  '@vitejs/plugin-basic-ssl': ^2.1.4
  '@vitejs/plugin-react-swc': ^4.2.2
  braces: ^3.0.3
  cli-columns: ^4.0.0
  clsx: ^2.1.1
  getopts: ^2.3.0
  globals: ^16.5.0
  immer: 11.1.3
  javascript-stringify: 2.1.0
  json-stringify-pretty-compact: 4.0.0
  lodash.clonedeep: ^4.5.0
  maath: ^0.10.8
  react: 19.2.1
  react-beforeunload: ^2.7.0
  react-dom: ^19.2.0
  react-grid-layout: 2.2.2
  react-reverse-portal: 2.3.0
  rxjs: ^7.8.2
  short-uuid: ^6.0.3
  tailwind-merge: ^3.4.0
  tailwindcss: ^4.1.17
  three: ^0.182.0
  tsx: ^4.21.0
  type-fest: ^5.3.1
  typescript: ~5.9.3
  uuid: ^13.0.0
  vite-bundle-analyzer: ^1.3.6
  zod: 4.1.13
  zustand: ^5.0.9

catalogMode: strict

publicHoistPattern:
  - react-resizable
