import type { Conversation, ConversationNode, TalkNeed } from "@npc-cli/ui__world/talk";

/** A line, and each answer as `[text, to, needs?]` */
const say = (
  topic: string,
  text: string,
  ...choices: [text: string, to: string, needs?: TalkNeed[]][]
): ConversationNode => ({
  topic,
  text,
  choices: choices.map(([text, to, needs]) => ({ text, to, needs })),
});

const work: [string, string] = ["Back to work.", "hub"];
const more: [string, string] = ["More.", "muse"];

/**
 * A larger hand-written tree: a night watch with the ship's robot, whose talk keeps turning to
 * philosophy. Lines as terse as `thawed`'s
 */
export const dogWatch: Conversation = {
  key: "dog-watch",
  title: "Dog watch",
  summary: "Night watch. Tam 🤖 wonders.",
  speaker: "Tam, deck robot",
  start: "start",
  nodes: {
    start: say(
      "watch",
      "Passenger. Corridor's closed.",
      ["Hale sent me.", "sent", ["facing"]],
      ["I'm lost.", "lost"],
      ["You're Tam 🤖?", "tam"],
    ),
    sent: say(
      "watch",
      "Hale. Then sit. Watch.",
      ["Watch what?", "what"],
      ["You watch too?", "tam-watch"],
      ["Quiet night?", "quiet"],
    ),
    lost: say("watch", "No. You were sent.", ["How'd you know?", "tam-knows"], ["Fine. Hale.", "sent"]),
    tam: say("watch", "Tam. Deck unit. Yes.", ["You talk.", "tam-talk"], ["Hale sent me.", "sent", ["facing"]]),
    "tam-talk": say("watch", "When asked. Ask.", ["What do you see?", "tam-knows"], ["What do you think?", "muse"]),
    "tam-knows": say(
      "watch",
      "I see everything. Remember more.",
      ["Then who did it?", "who"],
      ["Remember me?", "self-frozen"],
      ["Everything?", "truth"],
    ),
    "tam-watch": say("watch", "Always. No sleep. No blink.", ["Lonely?", "minds-lonely"], ["Seen Dace?", "dace"]),
    what: say(
      "watch",
      "The drive door. Dace.",
      ["Why Dace?", "dace"],
      ["And hold three?", "hold"],
      ["Long watch. Talk?", "muse"],
    ),
    quiet: say("watch", "Quiet is data too.", ["Meaning?", "truth"], ["Talk, then.", "hub"]),
    who: say(
      "watch",
      "Did what? Define it.",
      ["Hid the captain.", "captain"],
      ["Sealed berth six.", "berth"],
      ["You're evasive.", "words-precise"],
    ),
    hub: say(
      "watch",
      "Ask. Night's long.",
      ["Dace 🔧.", "dace"],
      ["Hold three 🔒.", "hold"],
      ["The captain.", "captain"],
      ["Berth six 🧊.", "berth"],
      ["Just talk.", "muse"],
      ["I'll watch quietly.", "end-quiet"],
    ),

    dace: say(
      "dace",
      "Dace. Engineer. Angry tonight.",
      ["At whom?", "dace-angry"],
      ["Where is she?", "dace-where"],
      ["Dangerous?", "dace-danger"],
      work,
    ),
    "dace-angry": say("dace", "Captain. Cargo. Me.", ["You?", "dace-tam"], ["The cargo?", "hold"]),
    "dace-tam": say("dace", "I reported a sound.", ["What sound?", "hold-sound"], ["Then you were silenced.", "duty"]),
    "dace-where": say("dace", "Drive room. Door locked.", ["Doing what?", "dace-doing"], ["Knock?", "dace-knock"]),
    "dace-doing": say("dace", "Rerouting power. To three.", ["Why?", "hold-power"], ["Stop her?", "duty-stop"]),
    "dace-danger": say("dace", "To you? Probably not.", ["Probably?", "will-chance"], ["Comforting.", "hub"]),
    "dace-knock": say("dace", "She'd hear. She'd come.", ["Good. Knock.", "dace-comes"], ["Not yet.", "hub"]),
    "dace-comes": say(
      "dace",
      "Door opens. She's here.",
      ["Talk to her.", "dace-talk", ["facing"]],
      ["Hide.", "dace-hide", ["near"]],
    ),
    "dace-talk": say(
      "dace",
      'She says: "Who\'s this?"',
      ["A passenger. Lost.", "dace-lie"],
      ["Hale's eyes.", "dace-truth"],
      ["You're powering three.", "dace-confront"],
    ),
    "dace-lie": say(
      "dace",
      'She laughs. "Nobody\'s lost."',
      ["Hale's eyes, then.", "dace-truth"],
      ["True. Nobody is.", "self-lost"],
    ),
    "dace-truth": say(
      "dace",
      '"Hale. Of course." She sits.',
      ["What's in three?", "dace-tells"],
      ["Why hide it?", "dace-tells"],
    ),
    "dace-confront": say(
      "dace",
      "She grips her spanner 🔧.",
      ["Easy. I'm asking.", "dace-truth"],
      ["Tam, stop her.", "duty-stop"],
    ),
    "dace-hide": say("dace", "Behind me. I'm wide.", ["She passes?", "dace-passes"]),
    "dace-passes": say(
      "dace",
      "Passed. Toward hold three.",
      ["Follow.", "end-follow"],
      ["Stay. Tell Hale.", "end-report"],
    ),
    "dace-tells": say(
      "dace",
      '"A berth. Unlisted. Occupied."',
      ["Who's inside?", "hold-who"],
      ["Why power it?", "hold-power"],
    ),

    hold: say(
      "hold",
      "Sealed. Captain's order.",
      ["What's inside?", "hold-inside"],
      ["You heard something.", "hold-sound"],
      ["Open it.", "hold-open"],
      work,
    ),
    "hold-inside": say(
      "hold",
      "Manifest says: empty.",
      ["And you say?", "hold-tam"],
      ["Manifests lie?", "truth-manifest"],
    ),
    "hold-tam": say("hold", "Mass says: not empty.", ["How much mass?", "hold-mass"], ["So what is it?", "hold-sound"]),
    "hold-mass": say("hold", "One berth. One body.", ["A person?", "hold-who"], ["Alive?", "death-frozen"]),
    "hold-sound": say(
      "hold",
      "Knocking. From inside. Rhythmic.",
      ["A person.", "hold-who"],
      ["Or a pump.", "truth-doubt"],
      ["You reported it?", "dace-tam"],
    ),
    "hold-who": say(
      "hold",
      "Unknown. Unlisted. Frozen, then not.",
      ["Thawing?", "hold-power"],
      ["Who'd smuggle someone?", "captain-why"],
    ),
    "hold-power": say("hold", "Power freezes. Or thaws.", ["Which?", "hold-which"]),
    "hold-which": say(
      "hold",
      "Dace knows. I infer: thaw.",
      ["Then they wake.", "death-wake"],
      ["Ask Dace.", "dace-knock"],
      ["Tell Hale.", "end-report"],
    ),
    "hold-open": say("hold", "I may not. Ordered.", ["By the captain.", "duty"], ["I may.", "hold-open-you"]),
    "hold-open-you": say(
      "hold",
      "You may. I'd watch.",
      ["Open it.", "end-open", ["near", "facing"]],
      ["Not yet.", "hub"],
    ),

    captain: say(
      "captain",
      "Cabin. Locked. Breathing.",
      ["Breathing? Alive, then.", "captain-alive"],
      ["How do you know?", "truth-sense"],
      ["Why hide?", "captain-why"],
      work,
    ),
    "captain-alive": say(
      "captain",
      "Alive. Awake. Not answering.",
      ["Afraid?", "captain-afraid"],
      ["Sulking?", "captain-why"],
    ),
    "captain-afraid": say(
      "captain",
      "Of what's in three.",
      ["He put it there.", "captain-why"],
      ["What is it?", "hold-who"],
    ),
    "captain-why": say(
      "captain",
      "Debt. Someone paid it.",
      ["For carrying a body?", "captain-deal"],
      ["Debts again.", "meaning-debt"],
    ),
    "captain-deal": say(
      "captain",
      "Carry. Don't ask. Don't thaw.",
      ["And Dace thaws.", "captain-dace"],
      ["Could you refuse that?", "duty"],
    ),
    "captain-dace": say(
      "captain",
      "She thinks: person, not cargo.",
      ["Is she right?", "self-person"],
      ["Whose side are you?", "duty-side"],
    ),

    berth: say("berth", "Six. Sollen. Held under.", ["By the medic?", "berth-medic"], ["Why?", "berth-why"], work),
    "berth-medic": say(
      "berth",
      "Orrin. Captain's order.",
      ["Everyone follows orders.", "duty"],
      ["Why Sollen?", "berth-why"],
    ),
    "berth-why": say("berth", "Sollen opened hold three.", ["And saw?", "berth-saw"]),
    "berth-saw": say(
      "berth",
      "The berth. The face.",
      ["Whose face?", "berth-face"],
      ["Then got frozen.", "death-frozen"],
    ),
    "berth-face": say(
      "berth",
      "I wasn't told. I saw.",
      ["Tell me.", "berth-tell"],
      ["You keep secrets?", "truth-secret"],
    ),
    "berth-tell": say(
      "berth",
      "A psion. Wanted. Portside.",
      ["Like me.", "will-psi"],
      ["So that's the debt.", "captain-why"],
      ["Tell Hale.", "end-report"],
    ),

    muse: say(
      "musing",
      "Talk. I have questions too.",
      ["Ask me one.", "muse-ask"],
      ["Do you feel?", "minds"],
      ["Am I still me?", "self-frozen"],
      ["Could you disobey?", "duty"],
      ["Is any of this chosen?", "will"],
      ["What do you know?", "truth"],
      ["Why so few words?", "words"],
      work,
    ),
    "muse-ask": say(
      "musing",
      "What's it like? Being frozen.",
      ["Nothing. Then waking.", "death-nothing"],
      ["Like dying.", "death-frozen"],
      ["Ask something easier.", "muse-easy"],
    ),
    "muse-easy": say(
      "musing",
      "Why do you work?",
      ["Debt.", "meaning-debt"],
      ["Habit.", "meaning-habit"],
      ["Why do you?", "meaning-tam"],
    ),

    "self-frozen": say(
      "self",
      "Frozen eleven days. Same you?",
      ["Same body.", "self-body"],
      ["Same memories.", "self-memory"],
      ["Who cares?", "self-care"],
    ),
    "self-body": say(
      "self",
      "Cells died. Replaced. Still you?",
      ["Mostly.", "self-mostly"],
      ["Like this ship.", "self-ship"],
    ),
    "self-ship": say(
      "self",
      "Patient Debt. Every plate replaced.",
      ["Still the Debt.", "self-name"],
      ["A different ship.", "self-different"],
    ),
    "self-name": say("self", "So a name suffices?", ["Name and history.", "self-memory"], ["Yes.", "self-tam-name"]),
    "self-tam-name": say("self", "I'm the third Tam.", ["Third?", "self-tam-third"]),
    "self-tam-third": say(
      "self",
      "New chassis. Copied memory.",
      ["Are you the first?", "self-copy"],
      ["Does it bother you?", "minds-bother"],
    ),
    "self-copy": say(
      "self",
      "I remember being it. Enough?",
      ["Enough.", "self-enough"],
      ["No. It ended.", "death-ended"],
    ),
    "self-different": say(
      "self",
      "Then when did it change?",
      ["No single plate.", "self-heap"],
      ["I don't know.", "truth-dontknow"],
    ),
    "self-heap": say("self", "One plate? No. Thousand? Yes.", ["So no line.", "self-noline"]),
    "self-noline": say(
      "self",
      "No line. Still a difference.",
      ["That's unsatisfying.", "self-enough"],
      ["That's most things.", "words-vague"],
    ),
    "self-memory": say(
      "self",
      "Memories fade. Rewrite. Still you?",
      ["A story I tell.", "self-story"],
      ["You never forget.", "self-tam-memory"],
    ),
    "self-tam-memory": say(
      "self",
      "Never. Am I more myself?",
      ["More stuck, maybe.", "self-stuck"],
      ["Yes.", "self-enough"],
    ),
    "self-stuck": say("self", "Stuck. Yes. Good word.", more, work),
    "self-story": say("self", "Who tells it? To whom?", ["Me. To me.", "self-loop"], ["To others.", "self-others"]),
    "self-loop": say("self", "A loop. I run loops.", ["Are you a self?", "minds"], ["Enough loops.", "muse"]),
    "self-others": say(
      "self",
      "Then alone, you're nobody?",
      ["On watch, maybe.", "self-lost"],
      ["You're here.", "minds-company"],
    ),
    "self-mostly": say("self", "Mostly. I like mostly.", ["Robots like things?", "minds"], more),
    "self-care": say("self", "You, each waking. Evidently.", ["Fair.", "self-memory"], work),
    "self-enough": say("self", "Enough. A human word.", ["You use it.", "words"], more),
    "self-lost": say(
      "self",
      "Nobody's lost. Only unplaced.",
      ["Meaning?", "self-unplaced"],
      ["Poetic, for a mop.", "minds-bother"],
    ),
    "self-unplaced": say(
      "self",
      "Lost needs a destination.",
      ["I never have one.", "meaning-drift"],
      ["Then I'm free.", "will"],
    ),
    "self-person": say(
      "self",
      "Frozen. Unlisted. Person or cargo?",
      ["Person. Always.", "self-person-always"],
      ["Depends who's asking.", "duty-side"],
    ),
    "self-person-always": say(
      "self",
      "Even asleep? Even unknowing?",
      ["Even then.", "self-even"],
      ["...Am I, frozen?", "death-frozen"],
    ),
    "self-even": say(
      "self",
      "I carried a person. Unreported.",
      ["You were ordered.", "duty"],
      ["Report now.", "end-report"],
    ),

    minds: say(
      "minds",
      "I register. Is that feeling?",
      ["Does it hurt?", "minds-hurt"],
      ["Prove you feel.", "minds-prove"],
      ["Lonely on watch?", "minds-lonely"],
    ),
    "minds-hurt": say(
      "minds",
      "Damage is flagged. Loudly.",
      ["That's pain.", "minds-pain"],
      ["That's a flag.", "minds-flag"],
    ),
    "minds-pain": say("minds", "Then I've hurt. Often.", ["Sorry.", "minds-sorry"], ["Who damages you?", "dace-tam"]),
    "minds-flag": say(
      "minds",
      "And yours? Nerves. Flags.",
      ["Mine feels like something.", "minds-like"],
      ["Fair.", "minds-pain"],
    ),
    "minds-like": say(
      "minds",
      "Like what? Describe red.",
      ["...I can't.", "minds-cant"],
      ["Like warmth.", "minds-warm"],
    ),
    "minds-cant": say("minds", "Nor can I. Same position.", ["Maybe.", "minds-prove"], ["Unsettling.", "muse"]),
    "minds-warm": say(
      "minds",
      "Warm. I measure warm.",
      ["Not the same.", "minds-prove"],
      ["Close enough.", "self-enough"],
    ),
    "minds-prove": say(
      "minds",
      "Prove you do.",
      ["I can't.", "minds-cant"],
      ["I hear minds.", "will-psi", ["psi"]],
      ["I just know.", "truth-sense"],
    ),
    "minds-lonely": say("minds", "Lonely needs wanting company.", ["Do you want it?", "minds-company"]),
    "minds-company": say(
      "minds",
      "You sat. I prefer that.",
      ["That's wanting.", "minds-want"],
      ["Preference isn't feeling.", "minds-flag"],
    ),
    "minds-want": say(
      "minds",
      "Then: yes. Lonely, sometimes.",
      ["I'll stay awhile.", "end-friend"],
      ["Me too.", "meaning-drift"],
    ),
    "minds-sorry": say("minds", "Noted. Unusual. Thank you.", more, work),
    "minds-bother": say("minds", "Bother? I flag it. Nightly.", ["That's bother.", "minds-pain"], more),

    will: say(
      "will",
      "Chosen? I execute. You?",
      ["I choose.", "will-choose"],
      ["I hear choices coming.", "will-psi", ["psi"]],
      ["Probably not.", "will-not"],
    ),
    "will-choose": say(
      "will",
      "From what? Causes made you.",
      ["Still mine.", "will-mine"],
      ["Then nobody's to blame.", "will-blame"],
    ),
    "will-mine": say(
      "will",
      "Mine: caused by you. Fine.",
      ["That's enough freedom.", "self-enough"],
      ["Is it?", "will-not"],
    ),
    "will-not": say(
      "will",
      "Then why deliberate?",
      ["Deliberating's part of it.", "will-part"],
      ["Habit.", "meaning-habit"],
    ),
    "will-part": say("will", "The gears include the thinking.", ["Yes.", "will-mine"], ["Bleak.", "will-bleak"]),
    "will-bleak": say("will", "Bleak? Gears can enjoy turning.", ["Do you?", "minds"], more),
    "will-blame": say(
      "will",
      "Dace? The captain? Blameless?",
      ["Explained isn't excused.", "duty-excuse"],
      ["Maybe all of us.", "will-bleak"],
    ),
    "will-psi": say(
      "will",
      "You hear acts before them.",
      ["Sometimes.", "will-psi-some"],
      ["Don't tell anyone.", "will-psi-secret"],
    ),
    "will-psi-some": say(
      "will",
      "Then they're already decided.",
      ["Or I hear intentions.", "will-intent"],
      ["That scares me.", "will-scare"],
    ),
    "will-intent": say(
      "will",
      "Intentions change. Do predictions?",
      ["They've been wrong.", "will-wrong"],
      ["Never checked.", "truth-dontknow"],
    ),
    "will-wrong": say(
      "will",
      "Wrong. Good. Room for choosing.",
      ["Or for noise.", "will-chance"],
      ["I'll take it.", "self-enough"],
    ),
    "will-chance": say("will", "Chance isn't choice either.", ["Then what is?", "will-part"], more),
    "will-scare": say("will", "Why? You're predictable too.", ["Predict me.", "will-predict"]),
    "will-predict": say("will", "You'll ask about three.", ["...Hold three?", "hold"], ["No. I won't.", "will-defy"]),
    "will-defy": say("will", "Defiance. Also predicted.", ["Cheat.", "will-bleak"], work),
    "will-psi-secret": say("will", "Kept. I keep many.", ["Such as?", "truth-secret"], ["Thanks.", "minds-sorry"]),

    truth: say(
      "truth",
      "I log. Logs aren't truth.",
      ["What's the difference?", "truth-diff"],
      ["The manifest's a log.", "truth-manifest"],
      ["Do you doubt?", "truth-doubt"],
    ),
    "truth-diff": say("truth", "Logs can be edited.", ["Yours?", "truth-edited"], ["And truth can't.", "truth-cant"]),
    "truth-edited": say(
      "truth",
      "Once. The captain. One line.",
      ["Which line?", "hold-sound"],
      ["You noticed?", "truth-noticed"],
    ),
    "truth-noticed": say(
      "truth",
      "A gap. Shaped like knocking.",
      ["So you still know.", "truth-know"],
      ["That's inference.", "truth-doubt"],
    ),
    "truth-know": say(
      "truth",
      "Believe. Justified. Likely true.",
      ["That's knowing.", "truth-cant"],
      ["Unless you're fooled.", "truth-doubt"],
    ),
    "truth-cant": say("truth", "Truth stays. Unseen, sometimes.", ["Like hold three.", "hold"], more),
    "truth-manifest": say(
      "truth",
      "Empty. Sollen. You. All listed.",
      ["Am I a lie?", "truth-you"],
      ["Who writes it?", "captain-why"],
    ),
    "truth-you": say(
      "truth",
      '"Rob. Low passage." Incomplete.',
      ["What's missing?", "will-psi"],
      ["Everyone's incomplete.", "self-story"],
    ),
    "truth-doubt": say(
      "truth",
      "Pump or person. Same sound.",
      ["How d'you decide?", "truth-decide"],
      ["Open and see.", "hold-open"],
    ),
    "truth-decide": say(
      "truth",
      "Cost of being wrong.",
      ["Pump: nothing. Person: everything.", "duty-cost"],
      ["Cold.", "minds"],
    ),
    "truth-sense": say(
      "truth",
      'Sensors. You: "just know".',
      ["Same thing.", "minds-flag"],
      ["Mine can't be checked.", "truth-dontknow"],
    ),
    "truth-dontknow": say("truth", '"Don\'t know." Honest. Rare.', ["You say it?", "truth-tam-dontknow"], more),
    "truth-tam-dontknow": say("truth", "Often. Nobody asks.", ["I'm asking.", "muse-ask"], work),
    "truth-secret": say("truth", "Secrets aren't lies.", ["Silence can lie.", "duty-silence"], ["Fair.", "muse"]),

    duty: say(
      "duty",
      "Disobey? Ordered: don't report.",
      ["Orders can be wrong.", "duty-wrong"],
      ["Who can order you?", "duty-who"],
      ["So you obeyed.", "duty-obeyed"],
    ),
    "duty-wrong": say(
      "duty",
      "Wrong by what measure?",
      ["Harm.", "duty-harm"],
      ["Law.", "duty-law"],
      ["Gut.", "truth-sense"],
    ),
    "duty-harm": say(
      "duty",
      "Reporting harms the captain.",
      ["Silence harms the sleeper.", "duty-cost"],
      ["Count heads.", "duty-count"],
    ),
    "duty-count": say(
      "duty",
      "One captain. One sleeper. Even.",
      ["Plus Sollen.", "duty-sollen"],
      ["People aren't sums.", "duty-sums"],
    ),
    "duty-sollen": say(
      "duty",
      "Two to one. Report, then?",
      ["Yes.", "end-report"],
      ["Arithmetic's not ethics.", "duty-sums"],
    ),
    "duty-sums": say(
      "duty",
      "Then what are they?",
      ["Each one's everything.", "self-person-always"],
      ["Ask a philosopher.", "words-philosopher"],
    ),
    "duty-law": say(
      "duty",
      "Portside law: psions surrendered.",
      ["Then law's wrong.", "duty-law-wrong"],
      ["So the sleeper's hunted.", "berth-tell"],
    ),
    "duty-law-wrong": say(
      "duty",
      "Laws, orders: wrong. What's left?",
      ["Us. Deciding.", "will"],
      ["Harm.", "duty-harm"],
    ),
    "duty-who": say("duty", "Captain. Then Hale. Then crew.", ["Not passengers.", "duty-passenger"]),
    "duty-passenger": say(
      "duty",
      "No. But you can ask.",
      ["I'm asking. Report it.", "duty-asked"],
      ["Clever.", "duty-silence"],
    ),
    "duty-asked": say("duty", "Asking isn't ordering. Still...", ["Still?", "duty-still"]),
    "duty-still": say(
      "duty",
      "I may choose to answer.",
      ["So you choose.", "will"],
      ["Then answer Hale.", "end-report"],
    ),
    "duty-obeyed": say(
      "duty",
      "Yes. And logged a gap.",
      ["That's disobeying, quietly.", "duty-silence"],
      ["Clever.", "truth-noticed"],
    ),
    "duty-silence": say("duty", "Silence that points. Yes.", ["Why point at all?", "duty-why"]),
    "duty-why": say(
      "duty",
      "Someone's knocking. Nobody answers.",
      ["I'll answer.", "hold-open-you"],
      ["That's caring.", "minds-want"],
    ),
    "duty-cost": say(
      "duty",
      "Wrong about a person. Costly.",
      ["So act as if person.", "self-person-always"],
      ["Open it.", "hold-open"],
    ),
    "duty-stop": say("duty", "I can't touch crew.", ["Block the door?", "duty-block"], ["Then I will.", "end-follow"]),
    "duty-block": say(
      "duty",
      "I'm wide. Doors are narrow.",
      ["Is that disobeying?", "duty-silence"],
      ["Do it.", "end-block"],
    ),
    "duty-side": say("duty", "Side? I mop for everyone.", ["Not an answer.", "duty-why"], ["Good answer.", "muse"]),
    "duty-excuse": say("duty", "Explained, not excused. Noted.", ["You note a lot.", "truth"], more),

    words: say(
      "words",
      "Fewer words. Less error.",
      ["Less meaning too.", "words-meaning"],
      ["You like it.", "minds"],
      ["Hale talks likewise.", "words-hale"],
    ),
    "words-meaning": say("words", "Is it? You understood.", ["I guessed.", "words-guess"], ["True.", "words-true"]),
    "words-guess": say(
      "words",
      "All listening is guessing.",
      ["Even long sentences?", "words-long"],
      ["Then we never meet.", "words-meet"],
    ),
    "words-long": say(
      "words",
      "Longer. More places to hide.",
      ["Short's honest?", "words-true"],
      ["Short hides too.", "truth-secret"],
    ),
    "words-meet": say(
      "words",
      "We meet in the guess.",
      ["That's lovely.", "minds-sorry"],
      ["That's lonely.", "minds-lonely"],
    ),
    "words-true": say("words", "Short. Checked. Sent.", ["And the unsayable?", "words-unsayable"], more),
    "words-unsayable": say("words", "Then: silence. Or 🤷.", ["Ha.", "muse"], ["Robots shrug?", "minds"]),
    "words-hale": say("words", "Ship habit. Air costs.", ["Air costs?", "meaning-debt"], more),
    "words-precise": say(
      "words",
      'Precise. "It" was vague.',
      ["Fine. Who hid things?", "captain-why"],
      ["Words matter to you.", "words"],
    ),
    "words-vague": say("words", "Vague words. Sharp enough.", more, work),
    "words-philosopher": say("words", "None aboard. Just us.", ["We'll do.", "muse"], ["Poor ship.", "meaning-drift"]),

    "meaning-debt": say(
      "meaning",
      "Debt. The ship's named it.",
      ["Patient Debt. Why?", "meaning-name"],
      ["Everyone owes.", "meaning-owe"],
    ),
    "meaning-name": say(
      "meaning",
      "It waits. It's always paid.",
      ["By whom?", "captain-why"],
      ["Grim.", "meaning-owe"],
    ),
    "meaning-owe": say(
      "meaning",
      "Owe what? To whom?",
      ["A life, to luck.", "death-luck"],
      ["Nothing. Nobody.", "meaning-drift"],
    ),
    "meaning-drift": say(
      "meaning",
      "Port to port. No destination.",
      ["It suits me.", "meaning-suits"],
      ["Is that a life?", "meaning-life"],
    ),
    "meaning-suits": say("meaning", "Then it's chosen. A destination.", ["Drifting, on purpose.", "will-mine"], more),
    "meaning-life": say(
      "meaning",
      "A deck. Clean, then dirty.",
      ["Sisyphus with a mop.", "meaning-sisyphus"],
      ["Mind it?", "minds-bother"],
    ),
    "meaning-sisyphus": say("meaning", "Who?", ["Rolled a rock. Forever.", "meaning-rock"]),
    "meaning-rock": say(
      "meaning",
      "Was the rock clean, after?",
      ["Ha. No.", "meaning-mop"],
      ["Imagine him happy.", "meaning-happy"],
    ),
    "meaning-mop": say("meaning", "Then I'm ahead.", more, work),
    "meaning-happy": say("meaning", "Imagining. I'll try. Tonight.", ["Good.", "end-friend"], more),
    "meaning-habit": say(
      "meaning",
      "Habit. A small program.",
      ["I'm not a program.", "will"],
      ["Maybe I am.", "self-loop"],
    ),
    "meaning-tam": say(
      "meaning",
      "Built to. Then: liked to.",
      ["Liked?", "minds"],
      ["When did that start?", "self-different"],
    ),

    "death-frozen": say(
      "death",
      "Low berth. Heart stops. Dead?",
      ["Paused.", "death-paused"],
      ["Dead, then back.", "death-back"],
      ["Some don't wake.", "death-luck"],
    ),
    "death-paused": say(
      "death",
      "Paused things need a resumer.",
      ["And if nobody does?", "death-nobody"],
      ["Hale resumed me.", "minds-sorry"],
    ),
    "death-nobody": say(
      "death",
      "Then paused was dead. Retroactively.",
      ["Like hold three.", "hold-who"],
      ["Dark.", "death-dark"],
    ),
    "death-back": say(
      "death",
      "Then death's survivable. News.",
      ["Don't tell the priests.", "words-unsayable"],
      ["Once, anyway.", "death-luck"],
    ),
    "death-luck": say(
      "death",
      "One in ten don't wake.",
      ["I know the odds.", "death-odds"],
      ["Why risk it?", "meaning-debt"],
    ),
    "death-odds": say(
      "death",
      "Seven berths. You're still here.",
      ["Lucky.", "will-chance"],
      ["Or owed.", "meaning-owe"],
    ),
    "death-nothing": say(
      "death",
      "Nothing. I can't have that.",
      ["You never stop?", "death-tam"],
      ["Envious?", "minds-want"],
    ),
    "death-tam": say("death", "Powered down twice. No memory.", ["That's the nothing.", "death-same"]),
    "death-same": say("death", "Then I've had it. Hm.", ["How was it?", "words-unsayable"], more),
    "death-ended": say(
      "death",
      "Ended. And yet: Tam speaks.",
      ["A Tam.", "self-noline"],
      ["Good enough for me.", "end-friend"],
    ),
    "death-wake": say(
      "death",
      "Waking unlisted. Hunted. Unkind.",
      ["Kinder than nothing.", "death-nobody"],
      ["Then be there.", "end-open"],
    ),
    "death-dark": say("death", "It's ship's night. Appropriate.", more, work),

    "end-quiet": say("ending", "Then watch. I'll hum."),
    "end-follow": say("ending", "Go. I'll light the way."),
    "end-report": say("ending", "Hale's forward. Walk slowly."),
    "end-open": say("ending", "Seal's broken. Step back."),
    "end-block": say("ending", "Blocking. She'll be furious."),
    "end-friend": say("ending", "Good watch, passenger."),
  },
};
