import type { Conversation, ConversationNode, TalkNeed } from "@npc-cli/ui__world/talk";

/** A line, and each answer as `[text, to, needs?]` */
const say = (
  topic: string,
  text: string,
  ...choices: [text: string, to: string, needs?: TalkNeed[]][]
): ConversationNode => ({
  topic,
  text,
  choices: choices.map(([text, to, needs]) => ({ text, to, needs })),
});

const tree = (
  key: string,
  title: string,
  summary: string,
  speaker: string,
  nodes: Conversation["nodes"],
): Conversation => ({
  key,
  title,
  summary,
  speaker,
  start: "start",
  nodes,
});

/**
 * Ten short hand-written trees, generic sci-fi, every line one to five words — to try the format and
 * the tests on, until trees are lore data
 */
export const conversations: Conversation[] = [
  tree("airlock", "Airlock", "Guard. Sealed door. Badge.", "airlock guard", {
    start: say("halt", "Halt. Badge.", ["Here. 🪪", "badge", ["near"]], ["Lost it.", "lost"], ["Who's asking?", "who"]),
    who: say("halt", "Dock security. You?", ["Crew. Cargo deck.", "badge", ["near"]], ["Nobody.", "push"]),
    badge: say(
      "halt",
      "Scanning... Expired.",
      ["Since when?", "expired"],
      ["Renew it?", "renew"],
      ["Let me through.", "push"],
    ),
    expired: say("halt", "Yesterday. Rules changed.", ["Whose rules?", "boss"], ["Fine. Renew.", "renew"]),
    renew: say("pass", "Thumb here.", ["👍.", "pass", ["near"]], ["No prints.", "push"]),
    pass: say("pass", "Valid. Mind the gap.", ["Thanks.", "end-through"]),
    lost: say("halt", "Then no entry.", ["Call my boss.", "boss"], ["Bribe?", "bribe"]),
    boss: say("halt", "Comms are down.", ["Convenient.", "push"], ["Then I'll wait.", "end-wait"]),
    bribe: say("halt", "Tempting. Cameras watch.", ["Shame.", "push"], ["Blind spot?", "blind"]),
    blind: say("halt", "Left side. Two minutes.", ["Deal.", "end-through", ["facing"]], ["Too risky.", "end-wait"]),
    push: say("halt", "Step back. Now.", ["Stepping back.", "end-wait"], ["Make me.", "end-stunned"]),
    "end-through": say("end", "Door's open. Go."),
    "end-wait": say("end", "Sit. Wait. Quietly."),
    "end-stunned": say("end", "Stunner ⚡ hums. Lights out."),
  }),

  tree("medbay", "Medbay", "Medic. Scan. Something's wrong.", "medic", {
    start: say("scan", "Sit. Arm out.", ["Sure.", "scan", ["near"]], ["Why?", "why"], ["Not today.", "end-refused"]),
    why: say("scan", "Routine. Everyone's scanned.", ["Everyone?", "outbreak"], ["Fine.", "scan", ["near"]]),
    outbreak: say("scan", "Since the outbreak.", ["What outbreak?", "symptoms"], ["Scan me.", "scan", ["near"]]),
    symptoms: say(
      "scan",
      "Fever. Then forgetting.",
      ["Forgetting what?", "forget"],
      ["Scan me. Now.", "scan", ["near"]],
    ),
    forget: say(
      "scan",
      "Names. Faces. Then yourself.",
      ["Scan me.", "scan", ["near"]],
      ["I'm leaving.", "end-refused"],
    ),
    scan: say("result", "Hm. Again.", ["What is it?", "result"], ["Problem?", "result"]),
    result: say("result", "Clean. Mostly.", ["Mostly?", "implant"], ["Good. Bye.", "end-clear"]),
    implant: say("result", "Old implant. Unregistered.", ["Not mine.", "whose"], ["Keep it quiet.", "quiet", ["psi"]]),
    whose: say("result", "Then whose?", ["Previous owner.", "end-report"], ["Don't know.", "end-report"]),
    quiet: say("result", "...Quiet. Yes. Of course.", ["Thank you.", "end-clear"]),
    "end-refused": say("end", "Then sign this 📝."),
    "end-clear": say("end", "Next!"),
    "end-report": say("end", "Reporting it. Sorry."),
  }),

  tree("cargo", "Cargo", "Quartermaster. Crates. Prices.", "quartermaster", {
    start: say("trade", "Buying or selling?", ["Buying.", "buy"], ["Selling.", "sell"], ["Looking.", "look"]),
    look: say("trade", "Look faster.", ["What's rare?", "rare"], ["Buying, then.", "buy"]),
    buy: say("trade", "Rations. Cells. Rope.", ["Cells 🔋.", "cells"], ["Rope.", "rope"], ["Anything else?", "rare"]),
    cells: say("trade", "Forty each.", ["Thirty.", "haggle"], ["Fine.", "end-bought"]),
    haggle: say("trade", "Thirty-eight. Final.", ["Thirty-five.", "haggle-more", ["facing"]], ["Deal.", "end-bought"]),
    "haggle-more": say("trade", "...Thirty-five. Don't tell.", ["Won't.", "end-bought"]),
    rope: say("trade", "Ten. Climbing somewhere?", ["Maybe.", "end-bought"], ["Mind yours.", "end-bought"]),
    sell: say("trade", "Show me.", ["This 🧭.", "compass", ["near"]], ["Nothing yet.", "end-nothing"]),
    compass: say("trade", "Antique. Five.", ["Fifty.", "lowball"], ["Fine.", "end-sold"]),
    lowball: say("trade", "Ten. Leave.", ["Fine.", "end-sold"]),
    rare: say(
      "rare",
      "Under the tarp. Ask nothing.",
      ["What's under?", "tarp", ["near"]],
      ["Nothing asked.", "end-nothing"],
    ),
    tarp: say("rare", "A cold box. Humming.", ["Alive?", "alive", ["psi"]], ["Not my business.", "end-nothing"]),
    alive: say("rare", "...How'd you know?", ["Lucky guess.", "end-nothing"], ["Open it.", "end-open"]),
    "end-bought": say("end", "Paid. Next."),
    "end-sold": say("end", "Pleasure. Mostly mine."),
    "end-nothing": say("end", "Then browse elsewhere."),
    "end-open": say("end", "Lid hisses. Eyes open."),
  }),

  tree("reactor", "Reactor", "Engineer. Alarm. Leak.", "engineer", {
    start: say("alarm", "Not now! Leak!", ["Help?", "help"], ["How bad?", "bad"], ["Leaving.", "end-left"]),
    bad: say("alarm", "Ten minutes bad.", ["Help, then.", "help"], ["Evacuate?", "evac"]),
    evac: say("alarm", "Pods jammed.", ["Then help.", "help"]),
    help: say("fix", "Hold this valve.", ["Holding.", "valve", ["near"]], ["Which valve?", "which"]),
    which: say("fix", "Red one! Red!", ["Holding red.", "valve", ["near"]]),
    valve: say("fix", "Turn on three.", ["One, two...", "turned", ["facing"]]),
    turned: say("fix", "Pressure dropping. Good.", ["What caused it?", "cause"], ["We did it.", "end-fixed"]),
    cause: say("fix", "Cut line. Deliberate.", ["Sabotage?", "sabotage"], ["Who'd do that?", "sabotage"]),
    sabotage: say(
      "fix",
      "Someone wants us drifting.",
      ["Who?", "suspect", ["psi"]],
      ["Tell the captain.", "end-report"],
    ),
    suspect: say("fix", "...You read that. From me.", ["You suspect the navigator.", "end-report"]),
    "end-left": say("end", "Coward. Fine. Go."),
    "end-fixed": say("end", "Breathe. We live."),
    "end-report": say("end", "Captain. Now. Run."),
  }),

  tree("bridge", "Bridge", "Captain. New orders.", "captain", {
    start: say("orders", "Late. Stand there.", ["Sorry, sir.", "orders", ["facing"]], ["Traffic.", "orders"]),
    orders: say(
      "orders",
      "Course change. Dark sector.",
      ["Why dark?", "why"],
      ["Understood.", "plot"],
      ["Refuse.", "refuse"],
    ),
    why: say("orders", "Cargo. Classified.", ["Classified from crew?", "secret"], ["Understood.", "plot"]),
    secret: say("orders", "Especially crew.", ["I could guess.", "guess", ["psi"]], ["Fine.", "plot"]),
    guess: say("orders", "...Stop that. Now.", ["Weapons?", "cargo"], ["Sorry.", "plot"]),
    cargo: say("orders", "Medicine. Stolen. Needed.", ["Then go.", "plot"], ["That's piracy.", "refuse"]),
    plot: say("duty", "Plot it. Quietly.", ["Plotted.", "end-plotted", ["near"]], ["Crew should know.", "refuse"]),
    refuse: say("duty", "Then the brig.", ["Wait. I'll plot.", "plot"], ["Brig, then.", "end-brig"]),
    "end-plotted": say("end", "Good. Dismissed."),
    "end-brig": say("end", "Escort them out."),
  }),

  tree("galley", "Galley", "Cook. Soup. Rumours.", "cook", {
    start: say(
      "food",
      "Hungry? Soup's grey.",
      ["Grey?", "grey"],
      ["Just rumours.", "rumour"],
      ["Bowl, please.", "bowl", ["near"]],
    ),
    grey: say("food", "Algae. Good for you.", ["Bowl, then.", "bowl", ["near"]], ["Pass.", "rumour"]),
    bowl: say("food", "Eat. Listen.", ["Listening.", "rumour"]),
    rumour: say(
      "rumour",
      "Captain's nervous. Engines too.",
      ["Engines nervous?", "engines"],
      ["Why the captain?", "captain"],
      ["Who else knows?", "who"],
    ),
    engines: say("rumour", "Rattling since port.", ["Engineer knows?", "who"], ["Bad sign.", "end-worried"]),
    captain: say("rumour", "Night calls. Locked door.", ["Calling whom?", "calls", ["psi"]], ["Gossip.", "end-gossip"]),
    calls: say("rumour", "...A buyer. You'd know.", ["I would.", "end-worried"]),
    who: say("rumour", "Everyone. Nobody says.", ["I'll say.", "end-worried"], ["Smart.", "end-gossip"]),
    "end-worried": say("end", "More soup? Comfort."),
    "end-gossip": say("end", "Suit yourself. Soup's cooling."),
  }),

  tree("stowaway", "Stowaway", "Hidden kid. Scared.", "stowaway", {
    start: say(
      "hide",
      "Don't shout. Please.",
      ["I won't.", "trust", ["facing"]],
      ["Who are you?", "who"],
      ["Security!", "end-caught"],
    ),
    who: say("hide", "Nobody. Hungry nobody.", ["How'd you board?", "board"], ["Hungry?", "food"]),
    trust: say("hide", "Promise?", ["Promise.", "board"], ["Depends.", "who"]),
    board: say("hide", "Crate. Three days.", ["Three days!", "food"], ["Why?", "why"]),
    food: say("hide", "Got food?", ["Here 🍫.", "fed", ["near"]], ["No.", "why"]),
    fed: say("hide", "Thanks. Really.", ["Why run?", "why"]),
    why: say("hide", "They'd send me back.", ["Back where?", "back", ["psi"]], ["Who would?", "back"]),
    back: say(
      "hide",
      "Mines. Below. Dark.",
      ["You can stay.", "end-hidden"],
      ["I'll get help.", "end-help"],
      ["Rules are rules.", "end-caught"],
    ),
    "end-hidden": say("end", "Quiet as dust. Promise."),
    "end-help": say("end", "...Okay. Hurry."),
    "end-caught": say("end", "Running footsteps. Gone."),
  }),

  tree("unit", "Unit", "Maintenance robot 🤖. Literal.", "maintenance unit", {
    start: say("query", "Query?", ["Status.", "status"], ["Open that door.", "door"], ["Are you alive?", "alive"]),
    status: say("query", "Nominal. Mop low.", ["Mop low?", "mop"], ["Ok.", "start"]),
    mop: say("query", "Mop fluid: twelve percent.", ["Refill it.", "refill"], ["Who cares?", "care"]),
    refill: say("query", "Authorisation required.", ["Authorised.", "voice", ["facing"]], ["Never mind.", "start"]),
    voice: say("query", "Voice mismatch. Denied.", ["Override 🔑.", "override", ["near"]], ["Rude.", "start"]),
    override: say("query", "Accepted. Refilling. Thank you.", ["Welcome.", "end-friend"]),
    door: say("door", "Door unspecified.", ["That 👉.", "that", ["facing"]], ["Any door.", "any"]),
    that: say("door", "Restricted. Captain's quarters.", ["Please?", "please"], ["Fine.", "start"]),
    please: say("door", "Please is not authorisation.", ["What is?", "voice"]),
    any: say("door", "Opening all doors.", ["No! Stop!", "end-chaos"]),
    alive: say("alive", "Define alive.", ["Wanting things.", "want"], ["Breathing.", "breathe"]),
    want: say("alive", "I want mop fluid.", ["Then alive.", "end-friend"], ["That's programming.", "care"]),
    breathe: say("alive", "Fans count?", ["Sure.", "end-friend"], ["No.", "care"]),
    care: say("alive", "Noted. Resuming mopping.", ["Bye.", "end-mop"]),
    "end-friend": say("end", "Logging you: friend."),
    "end-chaos": say("end", "Every door opens. Alarms."),
    "end-mop": say("end", "Mop. Mop. Mop."),
  }),

  tree("lockdown", "Lockdown", "Security. Alibi. Now.", "security officer", {
    start: say("alibi", "Lockdown. Where were you?", ["Galley.", "galley"], ["Sleeping.", "sleep"], ["Why?", "why"]),
    why: say("alibi", "Someone opened the vault.", ["Not me.", "sleep"], ["What's missing?", "missing"]),
    missing: say("alibi", "Telling you? No.", ["Fine. Galley.", "galley"]),
    galley: say("alibi", "Cook confirms?", ["Ask her.", "confirm"], ["She was busy.", "doubt"]),
    sleep: say("alibi", "Alone?", ["Yes.", "doubt"], ["Bunkmate saw.", "confirm"]),
    confirm: say("alibi", "Checking. Wait.", ["Waiting.", "checked"]),
    checked: say("alibi", "Confirmed. Lucky you.", ["Who's suspect?", "suspect"], ["Can I go?", "end-free"]),
    suspect: say("alibi", "Everyone. Still you.", ["Comforting.", "end-free"]),
    doubt: say("search", "Weak. Hands out.", ["Search me.", "search", ["near"]], ["I know who.", "know", ["psi"]]),
    search: say("search", "Clean. Hm.", ["Satisfied?", "end-free"]),
    know: say("search", "Talk.", ["Your deputy. Guilty thoughts.", "deputy"]),
    deputy: say(
      "search",
      "...Thoughts? Both of you.",
      ["Wait!", "end-cell"],
      ["Check him first.", "end-checking", ["facing"]],
    ),
    "end-free": say("end", "Go. Stay reachable."),
    "end-cell": say("end", "Cell three. Both."),
    "end-checking": say("end", "...Fine. Checking him."),
  }),

  tree("signal", "Signal", "Comms. Strange signal.", "comms officer", {
    start: say(
      "signal",
      "Listen. Hear that?",
      ["Static.", "static", ["near"]],
      ["Hear what?", "static", ["near"]],
      ["Busy.", "end-busy"],
    ),
    static: say("signal", "Not static. Pattern.", ["What pattern?", "pattern"], ["Coincidence.", "repeat"]),
    repeat: say("signal", "Repeating. Every ninety seconds.", ["Pattern, then.", "pattern"]),
    pattern: say("signal", "Primes. Then coordinates.", ["Whose?", "whose"], ["Coordinates where?", "where"]),
    where: say("signal", "Here. This ship.", ["Us?", "whose"], ["Reply?", "reply"]),
    whose: say("signal", "Unknown. Old code.", ["Reply?", "reply"], ["Tell the captain.", "end-report"]),
    reply: say(
      "reply",
      "Reply with what?",
      ["Primes back.", "sent", ["facing"]],
      ["Silence.", "end-silent"],
      ["👋.", "sent"],
    ),
    sent: say("reply", "Sent. Wait.", ["Anything?", "answer"]),
    answer: say("reply", "New pattern. A face.", ["Whose face?", "face", ["psi"]], ["Shut it off.", "end-off"]),
    face: say("reply", "...Yours. How?", ["I don't know.", "end-uncanny"]),
    "end-busy": say("end", "Your loss."),
    "end-report": say("end", "Captain'll want this."),
    "end-silent": say("end", "Listening only. Logging."),
    "end-off": say("end", "Off. Still humming."),
    "end-uncanny": say("end", "Screen dims. Static again."),
  }),
];
