name: Run a demo Node script
on: [workflow_dispatch]

jobs:
  execute-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          registry-url: https://registry.npmjs.org
          node-version-file: 'package.json'
          cache: 'pnpm'
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run a Node script
        run: pnpm noop